# The numpy.random package

## 1. Introduction to the package

Numpy.random is a sub-package of numpy. It is used to generate pseudo-random numbers for use in simulations. 
Pseudo-random numbers are computer generated numbers that have properties that [approximate the properties of random numbers.](https://www.random.org/randomness/)

## 2. Simple Random Data and Permutations

### Simple Random Data

Some simple functions in numpy.random return simple random data where all [floating point](https://www.geeksforgeeks.org/python-float-type-and-its-methods/) numbers between 0 and 1 (where 1 is excluded) are equally likely to be returned. THe rand() function, for example, will populate an array of your choosing with such numbers.

Here's and example of a 3 x 4 array: 

In [2]:
import numpy as np ## import numpy package
np.random.rand(3,4) ## generate 3 arrays each containing 4 random floats between 0 (inclusive) and 1(exclusive)

array([[0.10970468, 0.89647087, 0.64225601, 0.73669549],
       [0.1274835 , 0.35639683, 0.53694048, 0.92064319],
       [0.65897662, 0.23370229, 0.46586231, 0.13754468]])

The randint() function on the other hand will return random integers in a specified interval from low(inclusive) to high (exclusive). The shape of the array can also be specified. 

Here's an example of a 2 x 6 array with values between 10 and 19 (inclusive).

In [1]:
import numpy as np
np.random.randint(10,20, size = (2,6)) ## generate 2 arrays each containing 6 random integers between 10 (inclusive) and 20 (exclusive)

array([[10, 15, 17, 13, 19, 11],
       [14, 14, 18, 19, 11, 14]])

### Permutations

There are two functions that randomly shuffle the contents of an array in a sinilar fashion.

The "shuffle()" function shuffles the contents of an array as follows:

In [3]:
import numpy as np
arr = [1,2,3,4,5,6,7,8,9] ## create array containing integers sequenced 1-9 and assign to variable arr
np.random.shuffle(arr) ## shuffle contents of arr
arr ## display arr

[1, 3, 6, 8, 4, 9, 2, 7, 5]

If an array contains a list of sub-arrays, only the list will be shuffled, not the contents 
of each individual array i.e. the first dimension of any multi-dimensional array will be shuffled.

In [5]:
import numpy as np 
arr = [[1,2,3], [4,5,6], [7,8,9]] ## create 2-dimensional array and assign to variable arr
np.random.shuffle(arr) ## shuffle contents of 1st dimension of arr
arr  ## display shuffled array

[[4, 5, 6], [7, 8, 9], [1, 2, 3]]

The "permutation()" function returns a shuffled copy of the array. The "shuffle()" function, however, changes the state of the array that is passed as an argument. We can see how "permutation()" differs from "shuffle()" in the next 2 pieces of code.  

In [6]:
import numpy as np 
arr = [[1,2,3], [4,5,6], [7,8,9]] ## create 2-dimensional array and assign to variable arr
np.random.permutation(arr) ## display shuffled copy of arr


array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
import numpy as np 
arr = [[1,2,3], [4,5,6], [7,8,9]] ## create 2-dimensional array and assign to variable arr
np.random.permutation(arr) ## make shuffled copy of arr
arr  ## display unshuffled original array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## 3. Five "Distributions" Functions

### Binomial Distribution

A binomial experiment is an experiment that consists of a number of repeated trials that satisfy the following conditions;
* There are only two possible outcomes, one of which is typically called the succesful outcome.
* The probabilty of success(denoted by p) is the same for each trial.
* The outcome of any one trial is not affected by the outcome of any others.
An example of a binomial experiment is a coin flip; In this case p = 1/2 or 0.5.

A binomial random variable is the number of successful outcomes in a given number of trials of a binomial experiment.  
A binomial distribution is the probability distribution of a binomial random variable.

### Uniforn Distribution

### Normal Distribution

### Poisson Distribution

### Exponential Distribution

## 4. Seeds